<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('invoices', function (Blueprint $table) {
            $table->id();
            
            $table->unsignedBigInteger('contractor_id');
            $table->foreign('contractor_id')->references('id')->on('users')->onDelete('cascade');


            // $table->unsignedBigInteger('owner_id');
            // $table->foreign('owner_id')->references('id')->on('users')->onDelete('cascade');

            $table->unsignedBigInteger('contract_type_id')->nullable();
            $table->foreign('contract_type_id')->references('id')->on('contract_types')->onDelete('cascade');

            $table->unsignedBigInteger('created_by');
            $table->foreign('created_by')->references('id')->on('users')->onDelete('cascade');

            $table->unsignedBigInteger('assigned_to')->nullable();
            $table->foreign('assigned_to')->references('id')->on('users')->onDelete('cascade');
 
            $table->bigInteger('unique_no')->comment('autogenerated');
            $table->string('contract_number');
            $table->string('epcms')->comment('from contract_number');
            $table->string('owners')->comment('from contract_number');
            $table->string('barcode');
            $table->string('invoice_no');
            // $table->string('purchase_order_number');
            $table->string('currency')->nullable()->default('INR');
            $table->string('ra_bill_number');
            $table->text('description')->nullable();
            $table->float('basic_amount',14,2);
            $table->float('gst_amount',14,2);
            $table->float('total_amount',14,2);
            $table->float('paid_amount',14,2);
            $table->enum('invoice_type',['services','supply','Running Account Bill','Final Bill','Mobilization/Advance']);
            $table->string('vendor_name');
            $table->string('vendor_contact_number')->nullable();
            $table->string('vendor_contact_email');
            $table->string('package');
            $table->string('notes',244)->nullable();
            $table->enum('status',['pending_with_epcm','pending_with_owner','pending_with_treasurer','returned_to_epcm','returned_to_owner','returned_to_contractor', 'approved','paid','resend','pending_with_owner_finance'])->default('pending_with_epcm');
            $table->text('uploaded_files');
            $table->date('approved_date')->nullable();
            $table->date('paid_date')->nullable();
            $table->date('invoice_date')->nullable();
            $table->enum('creator_user_type',[1,2,3,4])->nullable()->comment('creator user type 3 for epcm, 4 for contractor, 1 for admin, 2 for owner');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('invoices');
    }
};
